In [4]:
import numpy as np
import pandas as pd

sol_data = pd.read_csv('/home/supriya/pathcontext_CDS_v2x/v2/CDS_100fv.csv',dtype={'label':object} )
id=sol_data["ID"]
label=sol_data["label"]
length=len(sol_data["Vector_form"])
print(sol_data)
sol_data.head()

           ID                                        Vector_form  \
0       10001  tensor([ 0.8442, -0.1290, -0.5327, -0.2592, -2...
1       10005  tensor([-0.2265,  0.1280, -0.2671, -2.0719,  1...
2       10007  tensor([-0.2674,  0.7070, -1.3275,  0.5945,  0...
3       10010  tensor([-0.3335,  0.9948,  0.8199,  0.0948,  0...
4       10011  tensor([ 1.6318e+00,  1.3590e+00, -1.1600e+00,...
...       ...                                                ...
67672  121816  tensor([ 1.1055, -0.1945,  1.5373,  0.5558,  1...
67673  121818  tensor([ 2.0601, -1.0136, -0.7287,  1.4757,  0...
67674  121819  tensor([-3.9180e-01,  4.2220e-02,  7.7156e-01,...
67675  121820  tensor([-0.4542,  0.5358,  1.5186, -0.0603,  1...
67676  121821  tensor([ 1.5748, -0.1939, -1.1010,  1.1242,  0...

                    label
0      000000000000000100
1      000000000001000000
2      010000000000001000
3      000000010000000000
4      001001000001000000
...                   ...
67672  110000001001010000
67673  010000000000011100
67674  011001000001110000
67675  110000000000001001
67676  000000000000010000

[67677 rows x 3 columns]

,ID,Vector_form,label
0,10001,"tensor([ 0.8442, -0.1290, -0.5327, -0.2592, -2...",000000000000000100
1,10005,"tensor([-0.2265, 0.1280, -0.2671, -2.0719, 1...",000000000001000000
2,10007,"tensor([-0.2674, 0.7070, -1.3275, 0.5945, 0...",010000000000001000
3,10010,"tensor([-0.3335, 0.9948, 0.8199, 0.0948, 0...",000000010000000000
4,10011,"tensor([ 1.6318e+00, 1.3590e+00, -1.1600e+00,...",001001000001000000

In [5]:
import re
z=''
for j in range(201):
    if j==0:
        continue
    elif j!=200:
        z=z+'v'+str(j)+','
    else:
        z=z+'v'+str(j)
#print(z)
savefile = open('/home/supriya/pathcontext_CDS_v2x/v2/CDS_200fv.txt', 'a')
savefile.write(str('ID') +","+str(z)+ ","+'label'+'\n')
savefile.close()
    
for i in range(length):
    
    
    x = sol_data["Vector_form"][i]
    m = re.search('\[([^]]+)\]', x)
    if m:
        x = m.group(1)
    
#print(x)
    y=re.sub('[+\s]','', x)

    savefile = open('/home/supriya/pathcontext_CDS_v2x/v2/CDS_200fv.txt', 'a')
    savefile.write(str(id[i]) +","+str(y)+ ","+ str(label[i])+'\n')
    savefile.close()

In [59]:
import re
z=''
for j in range(500):
    if j==0:
        continue
    elif j!=499:
        z=z+'v'+str(j)+','
    else:
        z=z+'v'+str(j)
#print(z)
savefile = open('/home/supriya/split_cols_v2/ValB13.txt', 'a')
savefile.write(str('ID') +","+str(z)+ ","+'Error_Label'+'\n')
savefile.close()
    
for i in range(length):
    
    
    x = sol_data["Vector_form"][i]
    m = re.search('\[([^]]+)\]', x)
    if m:
        x = m.group(1)
    
#print(x)
    y=re.sub('[+\s]','', x)

    savefile = open('/home/supriya/split_cols_v2/ValB13.txt', 'a')
    savefile.write(str(id[i]) +","+str(y)+ ","+ str(label[i])+'\n')
    savefile.close()

In [6]:
import numpy as np
import pandas as pd

sol_data = pd.read_csv('/home/supriya/pathcontext_CDS_v2x/v2/CDS_200fv.csv',dtype={'label':object} )

print(sol_data)
sol_data.head()

           ID      v1       v2       v3       v4       v5        v6        v7  \
0       10001  0.8442 -0.12900 -0.53270 -0.25920 -2.87180 -0.463300 -1.166900
1       10005 -0.2265  0.12800 -0.26710 -2.07190  1.04980  0.735300 -1.278200
2       10007 -0.2674  0.70700 -1.32750  0.59450  0.19680 -1.441300  0.877200
3       10010 -0.3335  0.99480  0.81990  0.09480  0.75150 -1.345200  0.973100
4       10011  1.6318  1.35900 -1.16000  0.99895  1.46040 -0.023704 -0.853480
...       ...     ...      ...      ...      ...      ...       ...       ...
67672  121816  1.1055 -0.19450  1.53730  0.55580  1.65290 -1.228100  1.352500
67673  121818  2.0601 -1.01360 -0.72870  1.47570  0.65650  1.043000 -1.080200
67674  121819 -0.3918  0.04222  0.77156 -1.73960  0.11649  0.958210  0.087104
67675  121820 -0.4542  0.53580  1.51860 -0.06030  1.04390  0.646700 -0.819000
67676  121821  1.5748 -0.19390 -1.10100  1.12420  0.63340 -1.947200  1.492300

            v8       v9  ...     v192    v193    v194      v195    v196  \
0      0.10490  0.03570  ... -0.82420  0.2124 -0.9694  0.133200 -0.7157
1      1.18710 -0.78370  ...  1.10200  0.8404 -0.5747 -0.146900 -1.8702
2      0.71510 -1.82220  ...  1.25870 -0.4495  0.7043 -2.284800 -0.8562
3     -0.41810 -1.69510  ... -0.15210 -0.9168 -1.4352 -0.968700 -0.1536
4     -0.85303  0.63129  ... -0.19292 -1.2267 -2.0150 -0.657110 -2.1667
...        ...      ...  ...      ...     ...     ...       ...     ...
67672  3.33960 -2.09710  ...  0.34820 -1.2988 -1.1548  0.252000  0.4799
67673 -0.50450 -0.58200  ...  1.70190 -2.3696  0.9142  0.647700 -0.3341
67674  1.07230  0.96830  ...  0.58451 -1.7154  1.6311 -0.068965 -1.1825
67675 -2.70970  1.80270  ...  1.21690  1.7495  0.6087 -0.075300  2.2115
67676  0.28840  0.46610  ...  0.03470  0.0410  1.3142  3.052200  0.9865

           v197     v198     v199     v200               label
0     -1.615800 -1.54600  0.74550 -0.27690  000000000000000100
1      0.178800 -1.63480 -0.40690 -0.73350  000000000001000000
2     -1.136200 -1.87770 -0.34500  0.69950  010000000000001000
3     -0.409600 -0.49330  1.43460  0.69180  000000010000000000
4     -0.019809 -0.75128 -0.48730 -0.43978  001001000001000000
...         ...      ...      ...      ...                 ...
67672  1.608200 -0.42360  0.49040 -1.56470  110000001001010000
67673 -0.810500 -0.04930  2.06360 -0.58210  010000000000011100
67674  2.034600 -1.48530 -0.65242  1.46180  011001000001110000
67675 -1.097700  0.88230 -0.01870  1.92560  110000000000001001
67676  0.923000 -0.30150 -0.77410  1.23970  000000000000010000

[67677 rows x 202 columns]

,ID,v1,v2,v3,v4,v5,v6,v7,v8,v9,...,v192,v193,v194,v195,v196,v197,v198,v199,v200,label
0,10001,0.8442,-0.1290,-0.5327,-0.25920,-2.8718,-0.463300,-1.16690,0.10490,0.03570,...,-0.82420,0.2124,-0.9694,0.13320,-0.7157,-1.615800,-1.54600,0.7455,-0.27690,000000000000000100
1,10005,-0.2265,0.1280,-0.2671,-2.07190,1.0498,0.735300,-1.27820,1.18710,-0.78370,...,1.10200,0.8404,-0.5747,-0.14690,-1.8702,0.178800,-1.63480,-0.4069,-0.73350,000000000001000000
2,10007,-0.2674,0.7070,-1.3275,0.59450,0.1968,-1.441300,0.87720,0.71510,-1.82220,...,1.25870,-0.4495,0.7043,-2.28480,-0.8562,-1.136200,-1.87770,-0.3450,0.69950,010000000000001000
3,10010,-0.3335,0.9948,0.8199,0.09480,0.7515,-1.345200,0.97310,-0.41810,-1.69510,...,-0.15210,-0.9168,-1.4352,-0.96870,-0.1536,-0.409600,-0.49330,1.4346,0.69180,000000010000000000
4,10011,1.6318,1.3590,-1.1600,0.99895,1.4604,-0.023704,-0.85348,-0.85303,0.63129,...,-0.19292,-1.2267,-2.0150,-0.65711,-2.1667,-0.019809,-0.75128,-0.4873,-0.43978,001001000001000000